apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask-demo
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/nikhil-nirmale/poc-3.git
    targetRevision: HEAD
    path: ./s-1   # This tells Argo CD to look in the 's-1' folder

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated: {}   # Optional: for auto-sync (remove if you want manual sync)
