apiVersion: v1
kind: Service
metadata:
  name: main-service
  labels:
    app: main-app
spec:
  selector:
    app: main-app
  ports:
    - protocol: TCP
      port: 80          # External port to access the service
      targetPort: 8080  # Port your container listens on
  type: LoadBalancer   # Creates external IP for public access
