apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  labels:
    app: mongo
spec:
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: 27017       # Service port
      targetPort: 27017 # Container port
  type: ClusterIP      # Internal access only
